// priority: 100
//
// kubejs/startup_scripts/skills.js
// ---------------------------------
// Custom TensurJS skills that bridge Tensura magicule mechanics into
// Legendary Survival Overhaul (LSO) body systems. See Claude.md §1.
//
//   kubejs:thermoregulation   (Extra Skill)      - heat / cold magicule flow control
//   kubejs:purification       (Common Skill)     - spiritual digestion, thirst & dirty water
//   kubejs:adaptive_carapace  (Intrinsic Skill)  - per-limb magicule armament
//
// Skill tiers map onto Tensura mastery: an un-mastered skill is Tier 1,
// a mastered skill (ctx.instance.isMastered(entity)) is Tier 2 / "True" tier.
//
// TensurJS API (mod id tensura_kubejs, source in TensurJS-main/):
//   StartupEvents.registry(TensuraKubeJS.SKILL_REGISTRY, event => {
//     event.create('ns:id')            // default builder type; NO second argument
//       .name(..).description(..).type('extra'|'common'|'intrinsic'|...)
//       .icon('ns:skill/path')         // -> ns:textures/skill/path.png
//       .canBeToggled(bool|ctx=>bool).canTick(bool|ctx=>bool)
//       .onToggleOn(ctx).onToggleOff(ctx).onTick(ctx)
//       .onBeingDamaged(ctx=>bool)     // return false = cancel; amount is a copy
//       .onTakenDamage(ctx=>bool)      // ctx.setAmount(x) rescales the hit
//   ctx: instance, entity, isToggled(), mastery(), consumeMagicule(n)->bool, tell(msg)
//   damage ctx: source, target, amount(), setAmount(f)
//   Name/description lang keys are generated by the builder.
//
// Every LSO Java class is resolved lazily and null-checked, so a missing or
// renamed LSO class degrades to a no-op with one warning instead of
// crashing the server (Claude.md §4 NBT Safety).
//
// Rhino note: KubeJS's engine treats const/let as function-scoped, so
// declarations inside loop bodies use var.

// ---------------------------------------------------------------------
// 0. LSO wiring (the only block that should ever need edits)
// ---------------------------------------------------------------------
//   capabilityUtil  : LSO 2.3.x (Forge). The 2.4 NeoForge build may have
//                     moved to attachments; the script degrades gracefully.
//   thirstUtil      : LSO public API, static takeDrink(player, int, float).
//   temperatureUtil : LSO public API, static getWorldTemperature(level, pos)
//                     and getTemperatureEnum(float).
const JAVA = {
  // LSO 2.4 (NeoForge) = util.AttachmentUtil (confirmed in-game); 2.3 (Forge) = util.CapabilityUtil.
  capabilityUtil: ['sfiomn.legendarysurvivaloverhaul.util.AttachmentUtil', 'sfiomn.legendarysurvivaloverhaul.util.CapabilityUtil'],
  thirstUtil: 'sfiomn.legendarysurvivaloverhaul.api.thirst.ThirstUtil',
  temperatureUtil: 'sfiomn.legendarysurvivaloverhaul.api.temperature.TemperatureUtil'
}

// LSO ids referenced by the skills (all registered in
// sfiomn.legendarysurvivaloverhaul.registry.MobEffectRegistry / api.ModDamageTypes).
const LSO = {
  effects: {
    heatResistance: 'legendarysurvivaloverhaul:heat_resistance',
    coldResistance: 'legendarysurvivaloverhaul:cold_resistance',
    temperatureImmunity: 'legendarysurvivaloverhaul:temperature_immunity',
    heatStroke: 'legendarysurvivaloverhaul:heat_stroke',
    frostbite: 'legendarysurvivaloverhaul:frostbite',
    heatThirst: 'legendarysurvivaloverhaul:heat_thirst',
    coldHunger: 'legendarysurvivaloverhaul:cold_hunger',
    // LSO's dirty-water debuff (applied by ThirstUtil.takeDrink from the
    // drink's JSON effect list). LSO has no separate "parasites" effect.
    thirst: 'legendarysurvivaloverhaul:thirst'
  },
  // DamageType msgIds are "<modid>.<name>" (ModDamageTypes.bootstrap).
  damage: {
    hyperthermia: 'legendarysurvivaloverhaul.hyperthermia',
    hypothermia: 'legendarysurvivaloverhaul.hypothermia',
    dehydration: 'legendarysurvivaloverhaul.dehydration'
  },
  // TemperatureEnum: FROSTBITE 0-10, COLD 10-16, NORMAL 16-24, HOT 24-30,
  // HEAT_STROKE 30-40. 20 is the middle of NORMAL ("50% baseline").
  temperature: { optimal: 20.0 },
  // Hydration runs 0..20 like vanilla hunger.
  hydration: { max: 20 }
}

// ---------------------------------------------------------------------
// 1. Shared helpers
// ---------------------------------------------------------------------
const _classCache = {}
function loadJava(key) {
  if (_classCache[key] !== undefined) return _classCache[key]
  var clazz = null
  var names = Array.isArray(JAVA[key]) ? JAVA[key] : [JAVA[key]]
  for (var i = 0; i < names.length && !clazz; i++) {
    try { clazz = Java.loadClass(names[i]) } catch (e) { /* try next */ }
  }
  if (!clazz) console.warn(`[skills.js] Could not load ${names.join(' / ')} (${key}); related bridge disabled.`)
  _classCache[key] = clazz
  return clazz
}

function isServerPlayer(entity) {
  return entity && entity.isPlayer() && !entity.level.isClientSide()
}

// Tier helpers: 1 = base, 2 = mastered.
function tierOf(ctx) {
  return ctx.instance.isMastered(ctx.entity) ? 2 : 1
}

// --- Effects ---------------------------------------------------------
function applyEffect(entity, effectId, duration, amplifier) {
  try {
    entity.potionEffects.add(effectId, duration, amplifier, false, false)
  } catch (e) {
    console.warn(`[skills.js] could not apply ${effectId}: ${e}`)
  }
}

function removeEffect(entity, effectId) {
  try {
    if (entity.potionEffects.isActive(effectId)) entity.removeEffect(effectId)
  } catch (e) {
    // effect id not registered in this LSO build
  }
}

// Award a mastery point every `every` ticks the skill is active
// (same pattern Tensura addons use: instance tag "activatedTimes").
function tickMastery(ctx, every) {
  var tag = ctx.instance.getOrCreateTag()
  var t = tag.getInt('activatedTimes')
  if (t % every === 0) ctx.instance.getSkill().addMasteryPoint(ctx.instance, ctx.entity)
  tag.putInt('activatedTimes', t + 1)
}

// --- LSO per-player data (optional; every use is guarded) ------------
// The accessor method names differ between LSO builds; probe a list.
const ACCESSOR_NAMES = {
  temp: ['getTempCapability', 'getTemperatureCapability', 'getTempAttachment', 'getTemperatureAttachment',
    'getTemperature', 'getTemperatureData', 'getTempData', 'temperature'],
  thirst: ['getThirstCapability', 'getThirstAttachment', 'getThirst', 'getThirstData', 'getHydrationAttachment',
    'getHydration', 'thirst']
}
var _accessor = {}
function lsoAccessor(kind, player) {
  var util = loadJava('capabilityUtil')
  if (!util) return null
  if (_accessor[kind] === undefined) {
    _accessor[kind] = null
    var names = ACCESSOR_NAMES[kind]
    for (var i = 0; i < names.length && !_accessor[kind]; i++) {
      try { if (typeof util[names[i]] === 'function') _accessor[kind] = names[i] } catch (e) { /* not there */ }
    }
    if (!_accessor[kind]) console.warn(`[skills.js] LSO util class has no ${kind} accessor among [${names.join(', ')}]`)
  }
  if (!_accessor[kind]) return null
  try { return util[_accessor[kind]](player) } catch (e) { return null }
}

function lsoTempCapability(player) {
  return lsoAccessor('temp', player)
}

function hydrationLevel(player) {
  var thirst = lsoAccessor('thirst', player)
  if (!thirst) return NaN
  try {
    return Number(thirst.getHydrationLevel())
  } catch (e) {
    return NaN
  }
}

// Adds hydration through LSO's public API (clamped at max by LSO).
function addHydration(player, points) {
  if (!(points > 0)) return false
  var util = loadJava('thirstUtil')
  if (!util) return false
  try {
    util.takeDrink(player, points, 0.0)
    return true
  } catch (e) {
    console.warn(`[skills.js] ThirstUtil.takeDrink failed: ${e}`)
    return false
  }
}

// --- Environment -----------------------------------------------------
// "Extreme" = the Nether, or a spot whose LSO world temperature is outside
// the NORMAL band. Falls back to vanilla biome base temperature.
function inExtremeBiome(entity) {
  var level = entity.level
  if (dimensionId(level) == 'minecraft:the_nether') return true
  var util = loadJava('temperatureUtil')
  if (util) {
    try {
      var t = util.getWorldTemperature(level, entity.blockPosition())
      return String(util.getTemperatureEnum(t)) != 'NORMAL'
    } catch (e) {
      // fall through to vanilla biome check
    }
  }
  try {
    var temp = level.getBiome(entity.blockPosition()).value().getBaseTemperature()
    return temp <= 0.15 || temp >= 1.5
  } catch (e) {
    return false
  }
}

function dimensionId(level) {
  try {
    var d = level.dimension
    return String(d.location ? d.location() : d)
  } catch (e) {
    return ''
  }
}

function damageTypeId(source) {
  try {
    return String(source.getMsgId())
  } catch (e) {
    return ''
  }
}

// Damage that no physical coating can stop (vanilla msgIds of #bypasses_armor
// minus fall / falling blocks, which the carapace does absorb) plus LSO's.
const NON_PHYSICAL_DAMAGE = [
  'drown', 'starve', 'wither', 'outOfWorld', 'genericKill', 'magic', 'indirectMagic',
  'dryout', 'freeze', 'onFire', 'inFire', 'lava', 'hotFloor', 'sonic_boom', 'cramming',
  'inWall', 'dragonBreath', 'thorns',
  LSO.damage.hyperthermia, LSO.damage.hypothermia, LSO.damage.dehydration
]

// ---------------------------------------------------------------------
// 2. Skill registration
// ---------------------------------------------------------------------
StartupEvents.registry(TensuraKubeJS.SKILL_REGISTRY, event => {
  console.info(`[skills.js] registering custom skills in ${TensuraKubeJS.SKILL_REGISTRY}`)

  // -------------------------------------------------------------------
  // Thermoregulation (Extra Skill)
  //   Tier 1 - Thermal Resistance: halves hyper/hypothermia tick damage,
  //            neutralises biome temperature penalties (LSO resistance effects).
  //   Tier 2 - Absolute Thermal Control: LSO temperature_immunity effect,
  //            body temperature locked at optimal, temperature debuffs removed.
  //   Cost   - 2 magicules per 100 ticks while in an extreme biome.
  // -------------------------------------------------------------------
  var THERMO_DRAIN = 2.0
  var THERMO_DRAIN_INTERVAL = 100
  var THERMO_EFFECT_TICKS = 60

  function isThermalDamage(ctx) {
    var id = damageTypeId(ctx.source)
    return id == LSO.damage.hyperthermia || id == LSO.damage.hypothermia
  }

  event.create('kubejs:thermoregulation')
    .name('Thermoregulation')
    .description('Control the flow of heat and cold magicules within the body. Halves hyperthermia and hypothermia damage and neutralises biome temperature penalties. Mastered: complete immunity to temperature extremes and their debuffs. Drains 2 magicules per 5 seconds in extreme biomes.')
    .type('extra')
    .icon('kubejs:skill/extra/thermoregulation')
    .canBeToggled(true)
    .canTick(ctx => ctx.isToggled())
    .onToggleOff(ctx => {
      removeEffect(ctx.entity, LSO.effects.heatResistance)
      removeEffect(ctx.entity, LSO.effects.coldResistance)
      removeEffect(ctx.entity, LSO.effects.temperatureImmunity)
    })
    .onTick(ctx => {
      var player = ctx.entity
      if (!isServerPlayer(player)) return
      var tick = player.tickCount
      if (tick % 20 != 0) return // throttle: once a second

      var tier = tierOf(ctx)

      // Tier 1: LSO's own resistance effects offset ambient heat / cold.
      applyEffect(player, LSO.effects.heatResistance, THERMO_EFFECT_TICKS, tier - 1)
      applyEffect(player, LSO.effects.coldResistance, THERMO_EFFECT_TICKS, tier - 1)

      // Tier 2: full immunity effect, hard-lock body temperature, strip debuffs.
      if (tier >= 2) {
        applyEffect(player, LSO.effects.temperatureImmunity, THERMO_EFFECT_TICKS, 0)
        var cap = lsoTempCapability(player)
        if (cap) {
          try {
            if (Math.abs(Number(cap.getTemperatureLevel()) - LSO.temperature.optimal) > 0.01) {
              cap.setTemperatureLevel(LSO.temperature.optimal)
            }
          } catch (e) {
            // capability API differs in this LSO build; the immunity effect still applies
          }
        }
        removeEffect(player, LSO.effects.heatStroke)
        removeEffect(player, LSO.effects.frostbite)
        removeEffect(player, LSO.effects.heatThirst)
        removeEffect(player, LSO.effects.coldHunger)
      }

      // Passive drain only while exposed to extreme biomes.
      if (tick % THERMO_DRAIN_INTERVAL == 0 && inExtremeBiome(player)) {
        if (!ctx.consumeMagicule(THERMO_DRAIN)) {
          ctx.tell('Thermoregulation toggled off: not enough magicules.')
          ctx.instance.setToggled(false)
          ctx.instance.onToggleOff(player)
          ctx.instance.markDirty()
          return
        }
      }

      tickMastery(ctx, 30)
    })
    // Absolute Thermal Control: immune to LSO thermal damage (return false = cancel).
    .onBeingDamaged(ctx => {
      if (!ctx.isToggled() || !isThermalDamage(ctx)) return true
      return tierOf(ctx) < 2
    })
    // Thermal Resistance: halve LSO thermal damage.
    .onTakenDamage(ctx => {
      if (ctx.isToggled() && isThermalDamage(ctx) && tierOf(ctx) < 2) {
        ctx.setAmount(ctx.amount() * 0.5)
      }
      return true
    })

  // -------------------------------------------------------------------
  // Purification & Sustenance (Common Skill)
  //   - Cleanses LSO's dirty-water "thirst" debuff.
  //   - Hydration depletes 50% slower per tier (tier 1: half of lost points
  //     are refunded; tier 2: every lost point is refunded, see below).
  //   - Tier 2 (True Sustenance): converts magicules directly into hydration,
  //     removing the need to drink.
  // -------------------------------------------------------------------
  var SUSTENANCE_COST_PER_POINT = 5.0

  event.create('kubejs:purification')
    .name('Purification & Sustenance')
    .description('Spiritual digestion filters parasites from untreated or salt water and slows thirst by half. Mastered (True Sustenance): converts magicules directly into hydration, removing the need to drink.')
    .type('common')
    .icon('kubejs:skill/common/purification')
    .canBeToggled(true)
    .canTick(ctx => ctx.isToggled())
    .onToggleOn(ctx => {
      if (!isServerPlayer(ctx.entity)) return
      var level = hydrationLevel(ctx.entity)
      if (!isNaN(level)) ctx.instance.getOrCreateTag().putInt('lastHydration', level)
    })
    .onTick(ctx => {
      var player = ctx.entity
      if (!isServerPlayer(player)) return
      if (player.tickCount % 20 != 0) return

      var tier = tierOf(ctx)

      // Spiritual digestion: the dirty-water debuff never takes hold.
      removeEffect(player, LSO.effects.thirst)

      var current = hydrationLevel(player)
      if (!isNaN(current)) {
        var tag = ctx.instance.getOrCreateTag()
        var last = tag.contains('lastHydration') ? tag.getInt('lastHydration') : current

        if (current < last) {
          // Hydration dropped since last check. Refund half the loss at tier 1
          // (probabilistic per point => 50% slower on average), all of it at tier 2.
          var lost = last - current
          var refund = 0
          for (var i = 0; i < lost; i++) {
            if (tier >= 2 || Math.random() < 0.5) refund++
          }
          if (tier >= 2 && refund > 0) {
            // True Sustenance: hydration is paid for with magicules instead.
            if (!ctx.consumeMagicule(refund * SUSTENANCE_COST_PER_POINT)) refund = 0
          }
          if (refund > 0) addHydration(player, refund)
        }

        // True Sustenance also tops the bar back up from magicule reserves.
        if (tier >= 2) {
          var now = hydrationLevel(player)
          if (!isNaN(now) && now < LSO.hydration.max && ctx.consumeMagicule(SUSTENANCE_COST_PER_POINT)) {
            addHydration(player, 1)
          }
        }

        var after = hydrationLevel(player)
        tag.putInt('lastHydration', isNaN(after) ? current : after)
      }

      tickMastery(ctx, 60)
    })

  // -------------------------------------------------------------------
  // Adaptive Carapace / Magic Armament (Intrinsic Passive)
  //   - Per-limb damage reduction applied before LSO locational damage.
  //   - Flat resistance to blunt hits from giant mobs so they fall under
  //     LSO's limb-break threshold.
  // -------------------------------------------------------------------
  // Base reduction per limb; mastered skill adds CARAPACE_MASTERY_BONUS.
  var CARAPACE_DR = { head: 0.25, torso: 0.15, arms: 0.10, legs: 0.10 }
  var CARAPACE_MASTERY_BONUS = 0.10
  var CARAPACE_FLAT_VS_GIANTS = 4.0
  var GIANT_HEIGHT = 2.5

  // Best-effort limb inference from the damage source. LSO rolls the exact
  // limb later; this picks the limb the hit is most likely to land on.
  function inferLimb(source, victim) {
    var id = damageTypeId(source)
    if (id == 'fall' || id == 'stalagmite' || id == 'sweetBerryBush') return 'legs'
    if (id == 'fallingBlock' || id == 'fallingAnvil' || id == 'fallingStalactite') return 'head'
    if (id == 'flyIntoWall') return 'head'
    var attacker = source.getDirectEntity()
    if (attacker) {
      // Compare the attacker's eye height to the victim's to guess high / low hits.
      var dy = attacker.getEyeY() - victim.getY()
      if (dy > victim.getBbHeight() * 0.85) return 'head'
      if (dy < victim.getBbHeight() * 0.35) return 'legs'
      return victim.isBlocking() ? 'arms' : 'torso'
    }
    return 'torso'
  }

  function isGiantMob(attacker) {
    if (!attacker || !attacker.isLiving() || attacker.isPlayer()) return false
    var type = String(attacker.type)
    if (type.startsWith('legendarymonsters:')) return true
    return attacker.getBbHeight() >= GIANT_HEIGHT
  }

  event.create('kubejs:adaptive_carapace')
    .name('Adaptive Carapace')
    .description('A hardened magicule coating shields each limb. Reduces damage to the head, torso, arms and legs before locational damage is applied and resists fractures from blunt hits by giant monsters.')
    .type('intrinsic')
    .icon('kubejs:skill/intrinsic/adaptive_carapace')
    .canBeToggled(true)
    .canTick(ctx => ctx.isToggled())
    .onTick(ctx => {
      if (!isServerPlayer(ctx.entity)) return
      if (ctx.entity.tickCount % 20 != 0) return
      tickMastery(ctx, 120)
    })
    // onTakenDamage carries the real Changeable amount, so this is where the
    // reduction is applied. Always returns true (never cancels the hit).
    .onTakenDamage(ctx => {
      if (!ctx.isToggled()) return true
      var source = ctx.source
      if (!source) return true
      var id = damageTypeId(source)
      // Only physical hits get armament; environmental / thermal damage is Thermoregulation's job.
      if (NON_PHYSICAL_DAMAGE.indexOf(id) >= 0) return true

      var amount = Number(ctx.amount())
      if (isNaN(amount) || amount <= 0) return true
      var limb = inferLimb(source, ctx.entity)
      var dr = CARAPACE_DR[limb] || CARAPACE_DR.torso
      if (tierOf(ctx) >= 2) dr += CARAPACE_MASTERY_BONUS
      amount = amount * (1.0 - dr)

      // Fracture guard: giant blunt hits lose a flat chunk before LSO's limb check.
      // A direct hit has the attacker itself as the direct entity; a projectile does not.
      var attacker = source.getDirectEntity()
      var isMelee = attacker && source.getEntity() && attacker.equals(source.getEntity())
      if (isMelee && isGiantMob(attacker)) {
        amount = Math.max(0.0, amount - CARAPACE_FLAT_VS_GIANTS)
      }

      ctx.setAmount(amount)
      ctx.instance.getOrCreateTag().putString('lastLimb', limb)
      return true
    })

  console.info('[skills.js] registered kubejs:thermoregulation, kubejs:purification, kubejs:adaptive_carapace')
})
