// 放到整合包 kubejs/startup_scripts/ 里面。
// 改完 startup_scripts 后需要重启游戏；/reload 不会重新注册种族和技能。

StartupEvents.registry(TensuraKubeJS.RACE_REGISTRY, event => {
  event.create('tensura_kubejs:dog')
    .name('狗')
    .description('狗种族的初始形态。')
    .difficulty('easy')
    .startingRace(true)
    .randomStartingRace(true)
    .defaultEvolution('tensura_kubejs:tengu')
    .baseAura(300, 400)
    .baseMagicule(300, 400)
    .size(0)
    .maxHealth(4)
    .maxSpiritualHealth(20)
    .attack(1)
    .attackSpeed(0.05)
    .knockbackResistance(0)
    .movementSpeed(0.03)
    .swimSpeed(0)

  event.create('tensura_kubejs:tengu')
    .name('天狗')
    .description('由狗进化而来。进化要求：基础 EP 达到 1000。')
    .difficulty('intermediate')
    .previousEvolution('tensura_kubejs:dog')
    .defaultEvolution('tensura_kubejs:god_dog')
    .baseAura(900, 1100)
    .baseMagicule(900, 1100)
    .size(0.05)
    .maxHealth(8)
    .maxSpiritualHealth(40)
    .attack(2)
    .attackSpeed(0.1)
    .knockbackResistance(0.05)
    .movementSpeed(0.05)
    .swimSpeed(0.05)
    .epRequirement(1000)

  event.create('tensura_kubejs:god_dog')
    .name('神狗')
    .description('由天狗进化而来。进化要求：基础 EP 达到 3000。')
    .difficulty('hard')
    .previousEvolution('tensura_kubejs:tengu')
    .defaultEvolution('tensura_kubejs:immortal_dog')
    .baseAura(2500, 3000)
    .baseMagicule(2500, 3000)
    .size(0.1)
    .maxHealth(16)
    .maxSpiritualHealth(80)
    .attack(4)
    .attackSpeed(0.15)
    .knockbackResistance(0.1)
    .movementSpeed(0.08)
    .swimSpeed(0.1)
    .epRequirement(3000)

  event.create('tensura_kubejs:immortal_dog')
    .name('仙狗')
    .description('狗种族进化路线的最终形态。进化要求：基础 EP 达到 10000。')
    .difficulty('hard')
    .previousEvolution('tensura_kubejs:god_dog')
    .baseAura(6000, 7000)
    .baseMagicule(6000, 7000)
    .size(0.15)
    .maxHealth(24)
    .maxSpiritualHealth(160)
    .attack(6)
    .attackSpeed(0.2)
    .knockbackResistance(0.15)
    .movementSpeed(0.1)
    .swimSpeed(0.15)
    .epRequirement(10000)
})

StartupEvents.registry(TensuraKubeJS.SKILL_REGISTRY, event => {
  event.create('tensura_kubejs:summon_villager')
    .name('召唤村民')
    .type('extra')
    .icon('tensura_kubejs:skill/summon_villager')
    .description('按下技能键后消耗1000模素，召唤一只村民，冷却3秒。')
    .onPressed(ctx => {
      if (ctx.cooldown() > 0) return
      if (!ctx.consumeMagicule(1000)) return

      ctx.spawnEntity('minecraft:villager')
      ctx.setCooldown(3)
    })
})
